export const postsConstants = {

    CREATE_COMMENT: 'CREATE_COMMENT',
    GET_COMMENT: 'GET_COMMENT',
    DELETE_COMMENT: 'DELETE_COMMENT',
    UPDATE_COMMENT: 'UPDATE_COMMENT',
    GET_POST: 'GET_POST',
    CLOSE_POST: 'CLOSE_POST',
    LIKE_POST: 'LIKE_POST',
    CREATE_POST: 'CREATE_POST',
  
};