export const userConstants = {

    INIT: 'INIT',

    REGISTER_REQUEST: 'REGISTER_REQUEST',
 

    LOGIN_REQUEST: 'LOGIN_REQUEST',
   

    LOGOUT: 'LOGOUT',

    SEARCH: 'SEARCH',

    GET_CURRENT_USER: 'GET_CURRENT_USER',

    GET_USER_BY_ID: 'GET_USER_BY_ID',
    FOLLOW_OR_UNFOLLOW_USER: 'FOLLOW_OR_UNFOLLOW_USER',
    FOLLOWERS_FOLLOWING: 'FOLLOWERS_FOLLOWING',

    GET_USER_FEED: 'GET_USER_FEED',

    CHANGE_USER_STATUS:'CHANGE_USER_STATUS',

    DELETE_USER: 'DELETE_USER',

    LOADER_START:'LOADER_START',

    LOADER_STOP: 'LOADER_STOP',

  
};
